const FLUID_STOP_WORDS = new Set([
  "genuine",
  "original",
  "originale",
  "fluid",
  "oil",
  "oem",
  "жидкость",
  "масло",
  "оригинал",
  "оригинальное",
  "оригинальная",
]);

export type LocalFluidCandidate = {
  id: string;
  name: string;
  salePriceCents: number;
  uomName: string | null;
  packageVolume: string | null;
  markingMode: string | null;
  atf: string | null;
  oemAtf: string | null;
  searchText: string | null;
  availableUnits: number;
};

export type LocalFluidSelection = {
  source: "local_catalog";
  productId: string;
  productName: string;
  quantity: number;
  availableUnits: number;
  packageLiters: number;
  totalCents: number;
  compatibilityEvidence: string;
};

export type LocalFluidCandidateTrace = {
  productId: string;
  catalogName: string;
  compatible: boolean;
  availableQuantity: number;
  requiredQuantity: number;
  packageLiters: number;
  unitPriceCents: number;
  eligible: boolean;
  exclusionReason: "incompatible_specification" | "price_missing" | "stock_insufficient" | null;
};

export type LocalFluidSelectionEvaluation = {
  selected: LocalFluidSelection | null;
  candidates: LocalFluidCandidateTrace[];
};

/**
 * `fluidPreference` is generated by the model, so it must not by itself turn
 * off the local-compatible-fluid policy.  We honour an original-only choice
 * only when the employee has actually requested it in their message.
 */
export function employeeRequestedOriginalFluidOnly(message: string) {
  const source = String(message ?? "")
    .normalize("NFKC")
    .replace(/[ёЁ]/g, "е")
    .toLocaleLowerCase("ru-RU");

  return [
    /(?:только|исключительно|строго)\s+(?:оригинал\w*|genuine|oem\b)/u,
    /(?:нуж(?:ен|на|но)|став(?:ь|ьте)|использ(?:уй|уйте)|хочу|требую|предпочитаю)\s+(?:оригинал\w*|genuine|oem\b)/u,
    /(?:без|не\s+(?:предлагать|использовать))\s+(?:аналог\w*|заменител\w*)/u,
    /(?:оригинал\w*|genuine|oem)\s+(?:масл\w*|жидкост\w*)\s+(?:только|обязательно)/u,
  ].some((pattern) => pattern.test(source));
}

export function shouldRequireOriginalFluid(input: { fluidPreference: string | null | undefined; employeeRequestedOriginalOnly: boolean }) {
  return input.fluidPreference === "original_only" && input.employeeRequestedOriginalOnly;
}

function normalizedWords(value: string) {
  return value
    .normalize("NFKC")
    .replace(/[ёЁ]/g, "е")
    .toLocaleLowerCase("ru-RU")
    .replace(/cvtf/giu, "cvt")
    .replace(/[^\p{L}\p{N}.]+/gu, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

export function fluidSpecificationTokens(value: string) {
  return normalizedWords(value).filter((word) => !FLUID_STOP_WORDS.has(word));
}

/**
 * A slash surrounded by spaces is how the assistant represents a documented
 * alternative specification (for example, "SP-IV / SP4-M").  It is not the
 * same as a slash inside a manufacturer name such as "Hyundai/Kia".
 */
export function fluidSpecificationAlternatives(value: string) {
  const source = String(value ?? "").trim();
  const alternatives = source.split(/\s+\/\s+/u).map((part) => part.trim()).filter(Boolean);
  return alternatives.length > 1 ? alternatives : source ? [source] : [];
}

/** Token groups for the local-catalog prefilter; groups are alternatives, not cumulative requirements. */
export function fluidSpecificationSearchTokenGroups(value: string) {
  return fluidSpecificationAlternatives(value)
    .map((alternative) => fluidSpecificationTokens(alternative).slice(0, 8))
    .filter((tokens) => tokens.length >= 2 || tokens.some((token) => /\d/u.test(token)));
}

export function normalizeFluidSpecification(value: string) {
  return fluidSpecificationTokens(value).join(" ");
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function fluidSpecificationMatchIndex(source: string, requiredSpec: string) {
  const tokens = fluidSpecificationTokens(requiredSpec);
  if (tokens.length < 2) return -1;
  const pattern = tokens
    .map((token) => token === "cvt" ? "cvtf?" : escapeRegExp(token))
    .join("[^\\p{L}\\p{N}]{0,32}");
  return new RegExp(pattern, "iu").exec(source)?.index ?? -1;
}

export function fluidSpecificationExcerpt(sourceValue: string, requiredSpec: string, max = 360) {
  const source = String(sourceValue ?? "").trim();
  if (!source) return null;
  const matchingAlternative = fluidSpecificationAlternatives(requiredSpec).find((alternative) => fluidSpecificationMatchesSingle(source, alternative));
  if (!matchingAlternative) return null;
  const foundAt = fluidSpecificationMatchIndex(source, matchingAlternative);
  if (foundAt < 0) return source.length <= max ? source : `${source.slice(0, Math.max(1, max - 1))}…`;
  const start = Math.max(0, foundAt - Math.floor(max / 3));
  const end = Math.min(source.length, start + max);
  return `${start > 0 ? "…" : ""}${source.slice(start, end)}${end < source.length ? "…" : ""}`;
}

function specificationCodes(value: string) {
  return [...value.matchAll(/\b\d{3}(?:\.\d{1,3})+\b/g)].map((match) => match[0]);
}

function technicalText(candidate: Pick<LocalFluidCandidate, "atf" | "oemAtf" | "searchText">) {
  return [candidate.atf, candidate.oemAtf, candidate.searchText].filter(Boolean).join("\n");
}

function normalizedSourceVariants(source: string) {
  const normalized = normalizeFluidSpecification(source);
  // Catalogs commonly state a shared application as "Hyundai/Kia".  Removing
  // the joined second make preserves the stated specification (SP-IV remains
  // mandatory) while allowing a Hyundai-only request to match that evidence.
  return [
    normalized,
    normalized.replace(/\bhyundai kia\b/gu, "hyundai"),
    normalized.replace(/\bhyundai kia\b/gu, "kia"),
    normalized.replace(/\bkia hyundai\b/gu, "hyundai"),
    normalized.replace(/\bkia hyundai\b/gu, "kia"),
  ];
}

function fluidSpecificationMatchesSingle(source: string, requiredSpec: string) {
  const normalizedRequired = normalizeFluidSpecification(requiredSpec);
  const normalizedSource = normalizeFluidSpecification(source);
  if (!normalizedRequired || !normalizedSource) return false;
  if (normalizedSourceVariants(source).some((variant) => variant.includes(normalizedRequired))) return true;

  const codes = specificationCodes(requiredSpec);
  if (!codes.length || !codes.every((code) => source.toLocaleLowerCase("ru-RU").includes(code.toLocaleLowerCase("ru-RU")))) return false;
  const nonNumericTokens = fluidSpecificationTokens(requiredSpec).filter((token) => /\p{L}/u.test(token));
  return nonNumericTokens.length === 0 || nonNumericTokens.every((token) => normalizedSource.includes(token));
}

export function fluidSpecificationMatches(candidate: Pick<LocalFluidCandidate, "atf" | "oemAtf" | "searchText">, requiredSpec: string) {
  const source = technicalText(candidate);
  return fluidSpecificationAlternatives(requiredSpec).some((alternative) => fluidSpecificationMatchesSingle(source, alternative));
}

function localizedNumber(value: string) {
  const parsed = Number(value.replace(",", "."));
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

export function packageVolumeLiters(candidate: Pick<LocalFluidCandidate, "uomName" | "packageVolume" | "markingMode">) {
  const uom = String(candidate.uomName ?? "").trim().toLocaleLowerCase("ru-RU");
  if (candidate.markingMode === "BULK_OIL_FROM_MARKED_BARREL" || /^(?:л|литр(?:а|ов)?|l|liter|litre)$/iu.test(uom)) return 1;
  const source = String(candidate.packageVolume ?? "");
  const match = source.match(/(\d+(?:[.,]\d+)?)\s*(?:л|l|liter|litre)(?=\s|$|[,;/)])/iu);
  return match ? localizedNumber(match[1]) ?? 1 : 1;
}

function quantityForLiters(candidate: LocalFluidCandidate, requiredLiters: number) {
  const litersPerUnit = packageVolumeLiters(candidate);
  const isLiterUnit = litersPerUnit === 1 && (
    candidate.markingMode === "BULK_OIL_FROM_MARKED_BARREL" ||
    /^(?:л|литр(?:а|ов)?|l|liter|litre)$/iu.test(String(candidate.uomName ?? "").trim())
  );
  return {
    litersPerUnit,
    quantity: isLiterUnit ? Math.round(requiredLiters * 1000) / 1000 : Math.ceil(requiredLiters / litersPerUnit),
  };
}

function evidenceFor(candidate: LocalFluidCandidate, requiredSpec: string) {
  const source = technicalText(candidate);
  const exactExcerpt = fluidSpecificationExcerpt(source, requiredSpec, 240);
  if (exactExcerpt) return exactExcerpt;
  const tokens = fluidSpecificationTokens(requiredSpec);
  const normalizedSource = normalizeFluidSpecification(source);
  const normalizedNeedle = tokens.join(" ");
  const normalizedIndex = normalizedSource.indexOf(normalizedNeedle);
  if (normalizedIndex < 0) return requiredSpec;
  const words = normalizedSource.split(" ");
  const before = normalizedSource.slice(0, normalizedIndex).split(" ").length - 1;
  return words.slice(Math.max(0, before - 3), Math.min(words.length, before + tokens.length + 4)).join(" ");
}

export function evaluatePreferredLocalFluid(candidates: LocalFluidCandidate[], requiredSpec: string, requiredLiters: number): LocalFluidSelectionEvaluation {
  if (!Number.isFinite(requiredLiters) || requiredLiters <= 0 || !normalizeFluidSpecification(requiredSpec)) return { selected: null, candidates: [] };
  const evaluated = candidates.map((candidate) => {
    const { litersPerUnit, quantity } = quantityForLiters(candidate, requiredLiters);
    const compatible = fluidSpecificationMatches(candidate, requiredSpec);
    const exclusionReason = !compatible
      ? "incompatible_specification" as const
      : candidate.salePriceCents <= 0
        ? "price_missing" as const
        : candidate.availableUnits + 0.0001 < quantity
          ? "stock_insufficient" as const
          : null;
    return {
      candidate,
      litersPerUnit,
      quantity,
      totalCents: Math.round(candidate.salePriceCents * quantity),
      trace: {
        productId: candidate.id,
        catalogName: candidate.name,
        compatible,
        availableQuantity: candidate.availableUnits,
        requiredQuantity: quantity,
        packageLiters: litersPerUnit,
        unitPriceCents: candidate.salePriceCents,
        eligible: exclusionReason === null,
        exclusionReason,
      } satisfies LocalFluidCandidateTrace,
    };
  });
  const eligible = evaluated.filter((entry) => entry.trace.eligible);
  eligible.sort((left, right) => left.totalCents - right.totalCents || right.candidate.availableUnits - left.candidate.availableUnits || left.candidate.name.localeCompare(right.candidate.name, "ru"));
  const selected = eligible[0];
  if (!selected) return { selected: null, candidates: evaluated.map((entry) => entry.trace) };
  return { selected: {
    source: "local_catalog",
    productId: selected.candidate.id,
    productName: selected.candidate.name,
    quantity: selected.quantity,
    availableUnits: selected.candidate.availableUnits,
    packageLiters: selected.litersPerUnit,
    totalCents: selected.totalCents,
    compatibilityEvidence: evidenceFor(selected.candidate, requiredSpec),
  }, candidates: evaluated.map((entry) => entry.trace) };
}

export function selectPreferredLocalFluid(candidates: LocalFluidCandidate[], requiredSpec: string, requiredLiters: number): LocalFluidSelection | null {
  return evaluatePreferredLocalFluid(candidates, requiredSpec, requiredLiters).selected;
}
