import { normalizeAttributeValue, parseStoredAttributeValues, type ProductAttributeField } from "@/lib/product-attribute-values";

const FLUID_STOP_WORDS = new Set([
  "genuine",
  "original",
  "originale",
  "fluid",
  "oil",
  "oem",
  "жидкость",
  "масло",
  "оригинал",
  "оригинальное",
  "оригинальная",
]);

export type LocalFluidCandidate = {
  id: string;
  name: string;
  salePriceCents: number;
  uomName: string | null;
  packageVolume: string | null;
  markingMode: string | null;
  atf: string | null;
  oemAtf: string | null;
  searchText: string | null;
  availableUnits: number;
  sae?: string | null;
  oem?: string | null;
  acea?: string | null;
  apiSpec?: string | null;
  ilsac?: string | null;
};

export type LocalFluidSelection = {
  source: "local_catalog";
  productId: string;
  productName: string;
  quantity: number;
  availableUnits: number;
  packageLiters: number;
  totalCents: number;
  compatibilityEvidence: string;
};

export type LocalFluidCandidateTrace = {
  productId: string;
  catalogName: string;
  compatible: boolean;
  availableQuantity: number;
  requiredQuantity: number | null;
  packageLiters: number | null;
  unitPriceCents: number;
  eligible: boolean;
  exclusionReason: "incompatible_specification" | "price_missing" | "stock_insufficient" | "package_unknown" | null;
};

export type LocalFluidSelectionEvaluation = {
  selected: LocalFluidSelection | null;
  candidates: LocalFluidCandidateTrace[];
};

/**
 * `fluidPreference` is generated by the model, so it must not by itself turn
 * off the local-compatible-fluid policy.  We honour an original-only choice
 * only when the employee has actually requested it in their message.
 */
export function employeeRequestedOriginalFluidOnly(message: string) {
  const source = String(message ?? "")
    .normalize("NFKC")
    .replace(/[ёЁ]/g, "е")
    .toLocaleLowerCase("ru-RU");

  return [
    /(?:только|исключительно|строго)\s+(?:оригинал\w*|genuine|oem\b)/u,
    /(?:нуж(?:ен|на|но)|став(?:ь|ьте)|использ(?:уй|уйте)|хочу|требую|предпочитаю)\s+(?:оригинал\w*|genuine|oem\b)/u,
    /(?:без|не\s+(?:предлагать|использовать))\s+(?:аналог\w*|заменител\w*)/u,
    /(?:оригинал\w*|genuine|oem)\s+(?:масл\w*|жидкост\w*)\s+(?:только|обязательно)/u,
  ].some((pattern) => pattern.test(source));
}

export function shouldRequireOriginalFluid(input: { fluidPreference: string | null | undefined; employeeRequestedOriginalOnly: boolean }) {
  return input.fluidPreference === "original_only" && input.employeeRequestedOriginalOnly;
}

function normalizedWords(value: string) {
  return value
    .normalize("NFKC")
    .replace(/[ёЁ]/g, "е")
    .toLocaleLowerCase("ru-RU")
    .replace(/cvtf/giu, "cvt")
    .replace(/[^\p{L}\p{N}.]+/gu, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

export function fluidSpecificationTokens(value: string) {
  return normalizedWords(value).filter((word) => !FLUID_STOP_WORDS.has(word));
}

/**
 * A slash surrounded by spaces is how the assistant represents a documented
 * alternative specification (for example, "SP-IV / SP4-M").  It is not the
 * same as a slash inside a manufacturer name such as "Hyundai/Kia".
 */
export function fluidSpecificationAlternatives(value: string) {
  const source = String(value ?? "").trim();
  const alternatives = source.split(/\s+\/\s+/u).map((part) => part.trim()).filter(Boolean);
  return alternatives.length > 1 ? alternatives : source ? [source] : [];
}

const EXPLICIT_FLUID_SIGNATURE_PATTERNS = [
  /\b(?:aw|sp|dw)\s*[- ]?\s*(?:(?:\d+)(?:\s*[- ]?\s*[a-z0-9]{1,4})?|ii|iii|iv|v|vi)\b/giu,
  /\b(?:jws|mercon|dexron|lifeguardfluid)\s*[- ]?\s*[a-z0-9]+\b/giu,
  /\bg\s*\d{3}(?:\s*\d{3}){1,3}(?:\s*[a-z0-9]{1,3})?\b/giu,
  /\bwss\s*[- ]?[a-z0-9-]+\b/giu,
];

/**
 * An explicit approval such as AW-2 is sufficient compatibility evidence.
 * It must not be hidden merely because the catalog describes the gearbox
 * maker differently (or does not repeat it at all).
 */
export function explicitFluidSpecificationSignatures(value: string) {
  const source = String(value ?? "");
  return [...new Set(EXPLICIT_FLUID_SIGNATURE_PATTERNS.flatMap((pattern) => [...source.matchAll(pattern)].map((match) => normalizeFluidSpecification(match[0])).filter(Boolean)))];
}

/** Token groups for the local-catalog prefilter; groups are alternatives, not cumulative requirements. */
export function fluidSpecificationSearchTokenGroups(value: string) {
  const groups = fluidSpecificationAlternatives(value).flatMap((alternative) => [
    fluidSpecificationTokens(alternative).slice(0, 8),
    ...explicitFluidSpecificationSignatures(alternative).map((signature) => fluidSpecificationTokens(signature)),
  ]).filter((tokens) => tokens.length >= 2 || tokens.some((token) => /\d/u.test(token)));
  return groups.filter((tokens, index) => groups.findIndex((other) => other.join("\u0000") === tokens.join("\u0000")) === index);
}

export function normalizeFluidSpecification(value: string) {
  return fluidSpecificationTokens(value).join(" ");
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function fluidSpecificationMatchIndex(source: string, requiredSpec: string) {
  const tokens = fluidSpecificationTokens(requiredSpec);
  if (tokens.length < 2) return -1;
  const pattern = tokens
    .map((token) => token === "cvt" ? "cvtf?" : escapeRegExp(token))
    .join("[^\\p{L}\\p{N}]{0,32}");
  return new RegExp(pattern, "iu").exec(source)?.index ?? -1;
}

export function fluidSpecificationExcerpt(sourceValue: string, requiredSpec: string, max = 360) {
  const source = String(sourceValue ?? "").trim();
  if (!source) return null;
  const matchingAlternative = fluidSpecificationAlternatives(requiredSpec).find((alternative) => fluidSpecificationMatchesSingle(source, alternative));
  if (!matchingAlternative) return null;
  const foundAt = fluidSpecificationMatchIndex(source, matchingAlternative);
  if (foundAt < 0) return source.length <= max ? source : `${source.slice(0, Math.max(1, max - 1))}…`;
  const start = Math.max(0, foundAt - Math.floor(max / 3));
  const end = Math.min(source.length, start + max);
  return `${start > 0 ? "…" : ""}${source.slice(start, end)}${end < source.length ? "…" : ""}`;
}

function specificationCodes(value: string) {
  return [...value.matchAll(/\b\d{3}(?:\.\d{1,3})+\b/g)].map((match) => match[0]);
}

function technicalText(candidate: Pick<LocalFluidCandidate, "atf" | "oemAtf" | "searchText">) {
  return [candidate.atf, candidate.oemAtf].filter(Boolean).join("\n");
}

function containsTokenSequence(source: string, needle: string) {
  const sourceTokens = source.split(" ").filter(Boolean);
  const needleTokens = needle.split(" ").filter(Boolean);
  if (!needleTokens.length || needleTokens.length > sourceTokens.length) return false;
  return sourceTokens.some((_, start) => needleTokens.every((token, offset) => sourceTokens[start + offset] === token));
}

function normalizedSourceVariants(source: string) {
  const normalized = normalizeFluidSpecification(source);
  // Catalogs commonly state a shared application as "Hyundai/Kia".  Removing
  // the joined second make preserves the stated specification (SP-IV remains
  // mandatory) while allowing a Hyundai-only request to match that evidence.
  return [
    normalized,
    normalized.replace(/\bhyundai kia\b/gu, "hyundai"),
    normalized.replace(/\bhyundai kia\b/gu, "kia"),
    normalized.replace(/\bkia hyundai\b/gu, "hyundai"),
    normalized.replace(/\bkia hyundai\b/gu, "kia"),
  ];
}

function fluidSpecificationMatchesSingle(source: string, requiredSpec: string) {
  const normalizedRequired = normalizeFluidSpecification(requiredSpec);
  const normalizedSource = normalizeFluidSpecification(source);
  if (!normalizedRequired || !normalizedSource) return false;
  if (normalizedSourceVariants(source).some((variant) => containsTokenSequence(variant, normalizedRequired))) return true;

  const signatures = explicitFluidSpecificationSignatures(requiredSpec);
  if (signatures.some((signature) => containsTokenSequence(normalizedSource, signature))) return true;

  const codes = specificationCodes(requiredSpec);
  if (!codes.length || !codes.every((code) => source.toLocaleLowerCase("ru-RU").includes(code.toLocaleLowerCase("ru-RU")))) return false;
  const nonNumericTokens = fluidSpecificationTokens(requiredSpec).filter((token) => /\p{L}/u.test(token));
  return nonNumericTokens.length === 0 || nonNumericTokens.every((token) => normalizedSource.includes(token));
}

// Candidate discovery can be fuzzy. Compatibility uses positive structured
// declarations only; punctuation and suffixes remain significant.
const NEGATIVE_DECLARATION = /(?:не\s+(?:соответств|подход|совместим|рекоменд|одобрен)|запрещ|кроме|исключая|not\s+(?:approved|compatible|suitable|recommended)|incompatible|except|exclude|prohibit)/iu;
function safeSpecKey(value: string, field: ProductAttributeField) {
  const normalized = normalizeAttributeValue(field, value);
  const safe = ["CANONICAL", "SAFE_NORMALIZED", "VERIFIED_ALIAS"].includes(normalized.status) ? normalized.value : value;
  return safe.normalize("NFKC").toLocaleUpperCase("en-US").replace(/\s+/g, " ").trim();
}
function positiveDeclarationMatches(source: string | null | undefined, required: string, field: ProductAttributeField) {
  const requiredKey = safeSpecKey(required, field);
  const segments = parseStoredAttributeValues(source);
  // A negative statement for the required specification overrides positives.
  if (segments.some(segment => NEGATIVE_DECLARATION.test(segment) && fluidSpecificationMatchesSingle(segment, required))) return false;
  return segments.filter(segment => !NEGATIVE_DECLARATION.test(segment)).some(segment =>
    safeSpecKey(segment, field) === requiredKey);
}
export function fluidSpecificationMatches(candidate: Pick<LocalFluidCandidate, "atf" | "oemAtf" | "searchText">, requiredSpec: string) {
  if (NEGATIVE_DECLARATION.test(requiredSpec)) return false;
  const statements = parseStoredAttributeValues(technicalText(candidate));
  if (statements.some(segment => NEGATIVE_DECLARATION.test(segment) && (fluidSpecificationMatchesSingle(segment, requiredSpec) || /^применение запрещено$/iu.test(segment)))) return false;
  return positiveDeclarationMatches(candidate.atf, requiredSpec, "atf") || positiveDeclarationMatches(candidate.oemAtf, requiredSpec, "transmissionOem");
}
const ENGINE_OIL_FIELDS = [["sae", "engineSae"], ["oem", "engineOem"], ["acea", "acea"], ["apiSpec", "engineApi"], ["ilsac", "ilsac"]] as const;
type EngineOilRequirement = { value: string; field?: ProductAttributeField };

function engineOilRequirements(requirements: string): EngineOilRequirement[] {
  // Commas separate labelled requirements, never an OEM decimal or an atomic
  // slash. Unrecognised clauses remain mandatory; do not extract just the SAE.
  return parseStoredAttributeValues(requirements.replace(/,\s*(?=(?:SAE|ACEA|API|ILSAC)\s)/giu, "; ")).map(value => {
    const labelled = value.match(/^(SAE|ACEA|API|ILSAC)\s+(.+)$/iu);
    const field = labelled ? ({ SAE: "engineSae", ACEA: "acea", API: "engineApi", ILSAC: "ilsac" } as const)[labelled[1].toUpperCase() as "SAE" | "ACEA" | "API" | "ILSAC"] : undefined;
    let bare = labelled?.[2] ?? value;
    // Accept the explicitly requested base class only. ACEA has no universal
    // "higher" ordering: this must never substitute C3 or A7/B7 for A5.
    if (field === "acea") bare = bare.replace(/^(A5(?:\/B5)?)\s+(?:или\s+выше|or\s+(?:higher|above|better))$/iu, "$1");
    return { value: bare, field };
  });
}

export function engineOilSpecificationSearchTokenGroups(requirements: string) {
  return engineOilRequirementGroups(requirements)
    .filter(group => group.every(isConcreteEngineOilRequirement))
    .map(group => group.flatMap(({ value }) => fluidSpecificationTokens(value)))
    .filter(tokens => tokens.length > 0);
}

/** Semicolon/comma clauses are cumulative; explicit labelled alternatives are
 * local to their clause. Thus SAE remains mandatory on every alternative. */
function engineOilRequirementGroups(requirements: string): EngineOilRequirement[][] {
  const clauses = parseStoredAttributeValues(requirements.replace(/,\s*(?=(?:SAE|ACEA|API|ILSAC)\s)/giu, "; "));
  let groups: EngineOilRequirement[][] = [[]];
  for (const clause of clauses) {
    const alternatives = clause.split(/\s+(?:либо|или|or)\s+(?=(?:SAE|ACEA|API|ILSAC)\s)/iu).map(engineOilRequirements);
    // Do not silently discard constraints from an over-complex expression.
    if (groups.length * alternatives.length > 16) return [];
    groups = groups.flatMap(group => alternatives.map(alternative => [...group, ...alternative]));
  }
  return groups.filter(group => group.length > 0);
}

function isConcreteEngineOilRequirement(requirement: EngineOilRequirement) {
  // "Latest" is a manual placeholder, not an approval or a class. Even a
  // catalogue row with that same placeholder cannot establish compatibility.
  return !/(?:\b(?:latest|current|unknown|unspecified)\b|последн|актуальн|не\s+указан)/iu.test(requirement.value);
}

function engineOilDeclarationMatches(source: string | null | undefined, required: EngineOilRequirement, field: ProductAttributeField) {
  return parseStoredAttributeValues(source).some(segment => {
    const declaration = engineOilRequirements(segment)[0];
    if (!declaration || (declaration.field && declaration.field !== field) || NEGATIVE_DECLARATION.test(segment)) return false;
    const key = safeSpecKey(declaration.value, field);
    const requiredKey = safeSpecKey(required.value, field);
    if (key === requiredKey) return true;
    // A5 is the gasoline component of the combined ACEA A5/B5 declaration.
    // Preserve all other slash classes and edition suffixes as atomic values.
    // Source: ACEA 2016 Oil Sequences, A/B gasoline and light-duty diesel oils.
    return field === "acea" && requiredKey === "A5" && key === "A5/B5";
  });
}

export function engineOilSpecificationMatches(candidate: Pick<LocalFluidCandidate, "sae" | "oem" | "acea" | "apiSpec" | "ilsac"> & Partial<Pick<LocalFluidCandidate, "searchText">>, requirements: string) {
  const groups = engineOilRequirementGroups(requirements);
  const statements = parseStoredAttributeValues([...ENGINE_OIL_FIELDS.map(([key]) => candidate[key]), candidate.searchText].filter(Boolean).join("; "));
  if (NEGATIVE_DECLARATION.test(requirements) || statements.some(segment => /^применение запрещено$/iu.test(segment))) return false;
  return groups.some(required => required.every(isConcreteEngineOilRequirement)
    && !statements.some(segment => NEGATIVE_DECLARATION.test(segment) && required.some(spec => fluidSpecificationMatchesSingle(segment, spec.value)))
    && required.every(spec => ENGINE_OIL_FIELDS.some(([key, field]) => (!spec.field || spec.field === field) && engineOilDeclarationMatches(candidate[key], spec, field))));
}

function localizedNumber(value: string) {
  const parsed = Number(value.replace(",", "."));
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

export function packageVolumeLiters(candidate: Pick<LocalFluidCandidate, "uomName" | "packageVolume" | "markingMode">) {
  const uom = String(candidate.uomName ?? "").trim().toLocaleLowerCase("ru-RU");
  if (/^(?:л|литр(?:а|ов)?|l|liter|litre)$/iu.test(uom)) return candidate.markingMode === "PACKAGED_MARKED_GOOD" ? null : 1;
  if (candidate.markingMode === "BULK_OIL_FROM_MARKED_BARREL") return null;
  const source = String(candidate.packageVolume ?? "");
  const match = source.match(/(\d+(?:[.,]\d+)?)\s*(мл|ml|milliliters?|millilitres?|л|l|liters?|litres?)(?=\s|$|[.,;/)])/iu);
  if (!match) return null;
  const amount = localizedNumber(match[1]);
  return amount == null ? null : /^(?:мл|ml|milli)/iu.test(match[2]) ? amount / 1000 : amount;
}

export function quantityForLiters(candidate: Pick<LocalFluidCandidate, "uomName" | "packageVolume" | "markingMode">, requiredLiters: number) {
  const litersPerUnit = packageVolumeLiters(candidate);
  if (litersPerUnit == null || !Number.isFinite(requiredLiters) || requiredLiters <= 0) return { litersPerUnit: null, quantity: null, purchasedVolumeLiters: null, packageRemainderLiters: null };
  const isLiterUnit = litersPerUnit === 1 && (
    candidate.markingMode === "BULK_OIL_FROM_MARKED_BARREL" ||
    /^(?:л|литр(?:а|ов)?|l|liter|litre)$/iu.test(String(candidate.uomName ?? "").trim())
  );
  const quantity = isLiterUnit ? Math.ceil((requiredLiters - 1e-8) * 1000) / 1000 : Math.ceil((requiredLiters - 1e-8) / litersPerUnit);
  const purchasedVolumeLiters = Math.round(quantity * litersPerUnit * 1000) / 1000;
  return { litersPerUnit, quantity, purchasedVolumeLiters, packageRemainderLiters: Math.round((purchasedVolumeLiters - requiredLiters) * 1000) / 1000, billingMode: isLiterUnit ? "actual_consumption" as const : "whole_packages" as const };
}

function evidenceFor(candidate: LocalFluidCandidate, requiredSpec: string) {
  const source = [candidate.atf, candidate.oemAtf, candidate.oem, candidate.sae, candidate.acea, candidate.apiSpec, candidate.ilsac].filter(Boolean).join("; ");
  const exactExcerpt = fluidSpecificationExcerpt(source, requiredSpec, 240);
  if (exactExcerpt) return exactExcerpt;
  const tokens = fluidSpecificationTokens(requiredSpec);
  const normalizedSource = normalizeFluidSpecification(source);
  const normalizedNeedle = tokens.join(" ");
  const normalizedIndex = normalizedSource.indexOf(normalizedNeedle);
  if (normalizedIndex < 0) return requiredSpec;
  const words = normalizedSource.split(" ");
  const before = normalizedSource.slice(0, normalizedIndex).split(" ").length - 1;
  return words.slice(Math.max(0, before - 3), Math.min(words.length, before + tokens.length + 4)).join(" ");
}

export function evaluatePreferredLocalFluid(candidates: LocalFluidCandidate[], requiredSpec: string, requiredLiters: number, family = "transmission_fluid"): LocalFluidSelectionEvaluation {
  if (!Number.isFinite(requiredLiters) || requiredLiters <= 0 || !normalizeFluidSpecification(requiredSpec)) return { selected: null, candidates: [] };
  const evaluated = candidates.map((candidate) => {
    const { litersPerUnit, quantity } = quantityForLiters(candidate, requiredLiters);
    const compatible = family === "engine_oil" ? engineOilSpecificationMatches(candidate, requiredSpec) : fluidSpecificationMatches(candidate, requiredSpec);
    const exclusionReason = !compatible
      ? "incompatible_specification" as const
      : quantity == null
        ? "package_unknown" as const
        : candidate.salePriceCents <= 0
        ? "price_missing" as const
        : candidate.availableUnits + 0.0001 < quantity
          ? "stock_insufficient" as const
          : null;
    return {
      candidate,
      litersPerUnit,
      quantity,
      totalCents: Math.round(candidate.salePriceCents * (quantity ?? 0)),
      trace: {
        productId: candidate.id,
        catalogName: candidate.name,
        compatible,
        availableQuantity: candidate.availableUnits,
        requiredQuantity: quantity,
        packageLiters: litersPerUnit,
        unitPriceCents: candidate.salePriceCents,
        eligible: exclusionReason === null,
        exclusionReason,
      } satisfies LocalFluidCandidateTrace,
    };
  });
  const eligible = evaluated.filter((entry) => entry.trace.eligible);
  eligible.sort((left, right) => left.totalCents - right.totalCents || right.candidate.availableUnits - left.candidate.availableUnits || left.candidate.name.localeCompare(right.candidate.name, "ru"));
  const selected = eligible[0];
  if (!selected) return { selected: null, candidates: evaluated.map((entry) => entry.trace) };
  return { selected: {
    source: "local_catalog",
    productId: selected.candidate.id,
    productName: selected.candidate.name,
    quantity: selected.quantity!,
    availableUnits: selected.candidate.availableUnits,
    packageLiters: selected.litersPerUnit!,
    totalCents: selected.totalCents,
    compatibilityEvidence: `LocalProduct ${selected.candidate.id}: структурированное заявление совместимости. ${family === "engine_oil" ? ENGINE_OIL_FIELDS.filter(([key]) => selected.candidate[key]).map(([key, field]) => `${field}: ${selected.candidate[key]}`).join("; ") : evidenceFor(selected.candidate, requiredSpec)}`,
  }, candidates: evaluated.map((entry) => entry.trace) };
}

export function selectPreferredLocalFluid(candidates: LocalFluidCandidate[], requiredSpec: string, requiredLiters: number): LocalFluidSelection | null {
  return evaluatePreferredLocalFluid(candidates, requiredSpec, requiredLiters).selected;
}
